//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro_Tracker_Desktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodoro_Tracker_Desktop.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LONG BREAK.
        /// </summary>
        internal static string _long {
            get {
                return ResourceManager.GetString("long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHORT BREAK.
        /// </summary>
        internal static string _short {
            get {
                return ResourceManager.GetString("short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force blue color.
        /// </summary>
        internal static string ForceBlue {
            get {
                return ResourceManager.GetString("ForceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force green color.
        /// </summary>
        internal static string ForceGreen {
            get {
                return ResourceManager.GetString("ForceGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force other color.
        /// </summary>
        internal static string ForceOtherColor {
            get {
                return ResourceManager.GetString("ForceOtherColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force red color.
        /// </summary>
        internal static string ForceRed {
            get {
                return ResourceManager.GetString("ForceRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOCUS TIME.
        /// </summary>
        internal static string pomodoro {
            get {
                return ResourceManager.GetString("pomodoro", resourceCulture);
            }
        }
    }
}
